package com.baidu.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmp<M extends BaseEmp<M>> extends Model<M> implements IBean {

	public M setEId(java.lang.Integer eId) {
		set("e_id", eId);
		return (M)this;
	}
	
	public java.lang.Integer getEId() {
		return getInt("e_id");
	}

	public M setEName(java.lang.String eName) {
		set("e_name", eName);
		return (M)this;
	}
	
	public java.lang.String getEName() {
		return getStr("e_name");
	}

	public M setDId(java.lang.Integer dId) {
		set("d_id", dId);
		return (M)this;
	}
	
	public java.lang.Integer getDId() {
		return getInt("d_id");
	}

}
