package com.baidu.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDept<M extends BaseDept<M>> extends Model<M> implements IBean {

	public M setDId(java.lang.Integer dId) {
		set("d_id", dId);
		return (M)this;
	}
	
	public java.lang.Integer getDId() {
		return getInt("d_id");
	}

	public M setDName(java.lang.String dName) {
		set("d_name", dName);
		return (M)this;
	}
	
	public java.lang.String getDName() {
		return getStr("d_name");
	}

}
