package com.baidu.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePerson<M extends BasePerson<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPName(java.lang.String pName) {
		set("p_name", pName);
		return (M)this;
	}
	
	public java.lang.String getPName() {
		return getStr("p_name");
	}

	public M setPIdentity(java.lang.String pIdentity) {
		set("p_identity", pIdentity);
		return (M)this;
	}
	
	public java.lang.String getPIdentity() {
		return getStr("p_identity");
	}

}
