package com.baidu.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dept", "d_id", Dept.class);
		arp.addMapping("dog", "id", Dog.class);
		arp.addMapping("emp", "e_id", Emp.class);
		// Composite Primary Key order: id,p_identity
		arp.addMapping("person", "id,p_identity", Person.class);
		arp.addMapping("user", "id", User.class);
	}
}

