package com.baidu.model;

import com.baidu.model.base.BaseDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dept extends BaseDept<Dept> {
	public static final Dept dao = new Dept().dao();
}
