package com.baidu.model;

import com.baidu.model.base.BaseDog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dog extends BaseDog<Dog> {
	public static final Dog dao = new Dog().dao();
}
