package com.baidu.model;

import com.baidu.model.base.BaseEmp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Emp extends BaseEmp<Emp> {
	public static final Emp dao = new Emp().dao();
}
