package com.baidu.model;

import com.baidu.model.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person().dao();
}
